# helper_3d.py
from __future__ import annotations
from typing import Tuple, Dict, Optional

import torch
from torch import Tensor

from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from matplotlib.axes import Axes

# Reuse your 2D generator from helper.py
from helper import generate_transaxial_spect_geometry


# ---------------------------
# Geometry: 2D → 3D extrusion
# ---------------------------

def extrude_quads_to_hexahedra(
    quads_xy: Tensor,               # (N, 4, 2)
    z_min: float,
    z_max: float,
    dtype: torch.dtype = torch.float64,
    device: Optional[torch.device] = None,
) -> Tensor:
    """
    Convert each 2D quad (x,y) into an axis-aligned hexahedron by extruding along z.

    Vertex order (matches standard box order, and is relied upon downstream for
    detector *front-face* identification):
      0:(x0,y0,z_min) 1:(x1,y1,z_min) 2:(x2,y2,z_min) 3:(x3,y3,z_min)
      4:(x0,y0,z_max) 5:(x1,y1,z_max) 6:(x2,y2,z_max) 7:(x3,y3,z_max)

    For detector crystals generated by generate_transaxial_spect_geometry_3d,
    vertices 0 and 3 lie at the *inner* detector radius, and 1 and 2 at the
    *outer* radius. This implies that the quad [0,4,7,3] corresponds to the
    INNER radial face, which is used as the detector entrance/front surface
    in scanner_modeling.geometry_3d.
    """
    if device is None:
        device = quads_xy.device
    N = quads_xy.shape[0]
    z0 = torch.full((N, 4, 1), float(z_min), dtype=dtype, device=device)
    z1 = torch.full((N, 4, 1), float(z_max), dtype=dtype, device=device)
    lower = torch.cat([quads_xy.to(dtype), z0], dim=-1)  # (N,4,3)
    upper = torch.cat([quads_xy.to(dtype), z1], dim=-1)  # (N,4,3)
    hexes = torch.cat([lower, upper], dim=1).contiguous()  # (N,8,3)
    return hexes


def hexahedron_quads(hexes: Tensor) -> Tensor:
    """
    Return the 6 quad faces of each hexahedron.
    Input:
        hexes: (N, 8, 3) with vertex indices:
          0 1 2 3 (z_min face), 4 5 6 7 (z_max face)
    Faces (as quads, CCW outward in the local box coordinate system):
      z-: [0,1,2,3], z+:[4,5,6,7],
      y-: [0,1,5,4], y+:[3,2,6,7],
      x-: [0,4,7,3], x+:[1,2,6,5]

    IMPORTANT for scanner_modeling:

    - For detector hexahedra produced by generate_transaxial_spect_geometry_3d:
        * The x- face ([0,4,7,3]) is the INNER radial face (towards the FOV).
        * This is used as the "front" detector face for solid-angle calculations.
    """
    idx = torch.tensor(
        [
            [0, 1, 2, 3],  # z-
            [4, 5, 6, 7],  # z+
            [0, 1, 5, 4],  # y-
            [3, 2, 6, 7],  # y+
            [0, 4, 7, 3],  # x- (inner face for detectors)
            [1, 2, 6, 5],  # x+ (outer face for detectors)
        ],
        dtype=torch.long,
        device=hexes.device,
    )
    return hexes[:, idx, :]


def hexahedron_triangles(hexes: Tensor) -> Tensor:
    """
    Triangulate each quad face → 12 triangles per hexahedron.
    Output: (N*12, 3, 3)

    Note: The triangle orientation is inherited from the quad order.
    For the detector entrance face (inner radial face [0,4,7,3]), the two
    triangles are (0,4,7) and (0,7,3). Downstream, geometry_3d may flip
    triangle orientations to ensure that the "front" normal points roughly
    towards the FOV/isocenter before using them in solid-angle calculations.
    """
    quads = hexahedron_quads(hexes)  # (N,6,4,3)
    # split each quad [a,b,c,d] → (a,b,c) and (a,c,d)
    a = quads[:, :, 0, :]
    b = quads[:, :, 1, :]
    c = quads[:, :, 2, :]
    d = quads[:, :, 3, :]
    t1 = torch.stack([a, b, c], dim=-2)  # (N,6,3,3)
    t2 = torch.stack([a, c, d], dim=-2)  # (N,6,3,3)
    tris = torch.cat([t1, t2], dim=1).reshape(-1, 3, 3).contiguous()
    return tris


# -----------------------------------------
# 3D generator: reuse your 2D, then extrude
# -----------------------------------------

def generate_transaxial_spect_geometry_3d(
    *,
    pinhole_diameter_mm: float = 2.0,
    pinhole_opening_angle_deg: float = 27.0,
    n_pinholes: int = 18,
    collimator_ring_radius_mm: float = 215.0,
    collimator_thickness_mm: float = 20.0,
    detector_ring_radius_mm: float = 215.0 + 542.0,
    detector_thickness_mm: float = 6.0,
    detector_crystal_width_mm: float = 3.5,
    collimator_axial_mm: float = 20.0,     # axial depth (z extent) of collimator block
    detector_axial_mm: float = 6.0,        # axial depth (z extent) of detector block
    z_center_mm: float = 0.0,              # center of the system along z
    dtype: torch.dtype = torch.float64,
    device: Optional[torch.device] = None,
) -> Dict[str, Tensor]:
    """
    Build a 3D SPECT configuration by extruding your 2D layout along z.

    Returns a dict with hexahedra for each component:
      - 'detector_hexes': (N_det, 8, 3) float64
      - 'inner_coll_hexes': (N_in, 8, 3) float64
      - 'outer_coll_hexes': (N_out, 8, 3) float64
      - 'detector_tris': (N_det*12, 3, 3)  (triangulated surfaces)
      - 'collimator_tris': (N_all_coll*12, 3, 3)

    Vertex order is chosen such that for detectors:
      - vertices 0 and 3 are at the inner radius,
      - vertices 1 and 2 are at the outer radius,
      - the quad [0,4,7,3] is the inner radial (front) face.
    """

    # 1) Use your existing 2D generator
    det_2d, inner_coll_2d, outer_coll_2d = generate_transaxial_spect_geometry(
        pinhole_diameter_mm=pinhole_diameter_mm,
        pinhole_opening_angle_deg=pinhole_opening_angle_deg,
        n_pinholes=n_pinholes,
        collimator_ring_radius_mm=collimator_ring_radius_mm,
        collimator_thickness_mm=collimator_thickness_mm,
        detector_ring_radius_mm=detector_ring_radius_mm,
        detector_thickness_mm=detector_thickness_mm,
        detector_crystal_width_mm=detector_crystal_width_mm,
    )  # shapes: (N_det,4,2), (N_in,4,2), (N_out,4,2)

    if device is None:
        device = det_2d.device

    # 2) Extrude to z-depths centered at z_center_mm
    def _z_bounds(depth_mm: float) -> Tuple[float, float]:
        h = 0.5 * float(depth_mm)
        return (z_center_mm - h, z_center_mm + h)

    det_z0, det_z1 = _z_bounds(detector_axial_mm)
    col_z0, col_z1 = _z_bounds(collimator_axial_mm)

    detector_hexes = extrude_quads_to_hexahedra(
        det_2d.to(dtype=dtype, device=device),
        det_z0,
        det_z1,
        dtype=dtype,
        device=device,
    )
    inner_coll_hexes = extrude_quads_to_hexahedra(
        inner_coll_2d.to(dtype=dtype, device=device),
        col_z0,
        col_z1,
        dtype=dtype,
        device=device,
    )
    outer_coll_hexes = extrude_quads_to_hexahedra(
        outer_coll_2d.to(dtype=dtype, device=device),
        col_z0,
        col_z1,
        dtype=dtype,
        device=device,
    )

    # 3) Triangulate for plotting / intersections
    detector_tris = hexahedron_triangles(detector_hexes)  # (N_det*12,3,3)
    inner_coll_tris = hexahedron_triangles(inner_coll_hexes)
    outer_coll_tris = hexahedron_triangles(outer_coll_hexes)
    if inner_coll_tris.numel() or outer_coll_tris.numel():
        collimator_tris = torch.cat([inner_coll_tris, outer_coll_tris], dim=0)
    else:
        collimator_tris = inner_coll_tris

    return {
        "detector_hexes": detector_hexes,
        "inner_coll_hexes": inner_coll_hexes,
        "outer_coll_hexes": outer_coll_hexes,
        "detector_tris": detector_tris,
        "collimator_tris": collimator_tris,
    }


# ---------------------------
# Matplotlib 3D visualization
# ---------------------------

def plot_hexahedra_mpl3d(
    hexes: Tensor,
    ax: Axes,
    *,
    facecolor: str = "C0",
    edgecolor: str = "k",
    alpha: float = 0.35,
    wireframe: bool = False,
) -> Optional[Poly3DCollection]:
    """
    Render hexahedra as 6 quads each (optionally wireframe).
    """
    if hexes.numel() == 0:
        return None

    quads = hexahedron_quads(hexes)  # (N,6,4,3)
    faces = quads.reshape(-1, 4, 3).detach().cpu().tolist()
    coll = Poly3DCollection(
        faces,
        facecolors="none" if wireframe else facecolor,
        edgecolors=edgecolor,
        linewidths=0.6 if wireframe else 0.2,
        alpha=alpha,
    )
    ax.add_collection3d(coll)
    return coll


def autoscale_3d_to_points(ax: Axes, *point_sets: Tensor, margin: float = 0.05):
    """
    Autoscale a 3D axes to fit all provided point sets with a small margin.
    """
    pts = [p.reshape(-1, 3) for p in point_sets if (p is not None and p.numel() > 0)]
    if not pts:
        return
    P = torch.cat(pts, dim=0).detach().cpu()
    mins = P.min(dim=0).values
    maxs = P.max(dim=0).values
    center = (mins + maxs) / 2.0
    radius = (maxs - mins).max().item() * (0.5 + margin)
    if radius <= 0:
        radius = 1.0
    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(center[2] - radius, center[2] + radius)
    ax.set_box_aspect([1, 1, 1])
    ax.set_xlabel("X (mm)")
    ax.set_ylabel("Y (mm)")
    ax.set_zlabel("Z (mm)")
