#!/usr/bin/env python
"""
visualize_ppdf_3d.py

Full 3-D visualization of a PPDF volume generated by pymatcal.
Renders three independent panels:

  1. Orthogonal mid-plane slices  (XY / XZ / YZ at the volume centre)
  2. All-Z slice grid             (one panel per Z layer, shared colour scale)
  3. 3-D scatter                  (voxels above a percentile threshold,
                                   coloured and alpha-blended by PPDF value)

Supports both output formats:
  single-detector  – dataset key "ppdf_volume", shape (Nx, Ny, Nz)
  batch shard      – dataset key "ppdfs",       shape (N_det, Nx*Ny*Nz)

Usage examples
--------------
# Single-detector file (size not stored in the .h5 — supply it):
    python visualize_ppdf_3d.py ppdf_det_1_layout_0.h5 --fov-size 32 32 32

# Batch shard (reads size from attrs, pick detector row 3):
    python visualize_ppdf_3d.py ppdf_shard_00000_00024.h5 --det-idx 3

# Save all panels to ./figs/, top 5 %% of non-zero voxels in 3-D:
    python visualize_ppdf_3d.py ppdf_det_1_layout_0.h5 \\
        --fov-size 32 32 32 --threshold-pct 95 --save --outdir ./figs
"""

import argparse
import os
import sys

import h5py
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 — registers 3d projection


# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------

def load_ppdf_volume(h5_path: str, det_idx: int = 0):
    """
    Load one PPDF volume as an (Nx, Ny, Nz) float32 array.

    Returns
    -------
    vol  : np.ndarray  (Nx, Ny, Nz)
    meta : dict        Nx, Ny, Nz, sx, sy, sz (mm), target_detector, fmt
    """
    with h5py.File(h5_path, "r") as f:

        # ---- single-detector output (arg_ppdf_calculation_3d.py) ----------
        if "ppdf_volume" in f:
            vol = f["ppdf_volume"][()]          # (Nx, Ny, Nz)
            Nx, Ny, Nz = vol.shape
            tgt = int(f.attrs.get("target_detector", -1))
            sx = float(f.attrs.get("sx", np.nan))
            sy = float(f.attrs.get("sy", np.nan))
            sz = float(f.attrs.get("sz", np.nan))
            return vol.astype(np.float32), dict(
                Nx=Nx, Ny=Ny, Nz=Nz, sx=sx, sy=sy, sz=sz,
                target_detector=tgt, fmt="single",
            )

        # ---- batch-shard output (arg_ppdf_calculation_3d_batch.py) --------
        elif "ppdfs" in f:
            dset = f["ppdfs"]
            Nx = int(dset.attrs["Nx"])
            Ny = int(dset.attrs["Ny"])
            Nz = int(dset.attrs["Nz"])
            sx, sy, sz = np.array(dset.attrs["size_mm"], dtype=float)
            n_det, _ = dset.shape
            if not (0 <= det_idx < n_det):
                raise IndexError(
                    f"--det-idx {det_idx} is out of range "
                    f"(file has {n_det} detector rows)"
                )
            vol = dset[det_idx].reshape(Nx, Ny, Nz).astype(np.float32)
            start = int(dset.attrs.get("start_idx", 0))
            return vol, dict(
                Nx=Nx, Ny=Ny, Nz=Nz, sx=sx, sy=sy, sz=sz,
                target_detector=start + det_idx, fmt="batch",
            )

        else:
            raise KeyError(
                f"No recognised dataset in {h5_path}. "
                "Expected 'ppdf_volume' (single) or 'ppdfs' (batch)."
            )


# ---------------------------------------------------------------------------
# Panel 1 — Orthogonal mid-plane slices
# ---------------------------------------------------------------------------

def plot_orthogonal_slices(vol, meta, save=False, outdir="."):
    """Three panels: XY at z_mid, XZ at y_mid, YZ at x_mid."""
    Nx, Ny, Nz = meta["Nx"], meta["Ny"], meta["Nz"]
    sx, sy, sz = meta["sx"], meta["sy"], meta["sz"]
    det = meta["target_detector"]

    xi, yi, zi = Nx // 2, Ny // 2, Nz // 2

    slices = [
        (vol[:, :, zi],  [-sx/2, sx/2, -sy/2, sy/2], "X (mm)", "Y (mm)",
         f"XY  z = {(zi/Nz - 0.5)*sz:+.2f} mm"),
        (vol[:, yi, :],  [-sx/2, sx/2, -sz/2, sz/2], "X (mm)", "Z (mm)",
         f"XZ  y = {(yi/Ny - 0.5)*sy:+.2f} mm"),
        (vol[xi, :, :],  [-sy/2, sy/2, -sz/2, sz/2], "Y (mm)", "Z (mm)",
         f"YZ  x = {(xi/Nx - 0.5)*sx:+.2f} mm"),
    ]

    vmax = float(vol.max())
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    fig.suptitle(f"Orthogonal Mid-Plane Slices — Detector {det}", fontsize=13)

    for ax, (data, extent, xlabel, ylabel, title) in zip(axes, slices):
        im = ax.imshow(
            data.T,
            origin="lower",
            extent=extent,
            cmap="viridis",
            vmin=0,
            vmax=vmax,
            interpolation="nearest",
        )
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        plt.colorbar(im, ax=ax, label="PPDF", fraction=0.046, pad=0.04)

    plt.tight_layout()
    _save_or_show(fig, save, outdir, f"ppdf_orthogonal_det{det}.png")


# ---------------------------------------------------------------------------
# Panel 2 — All-Z slice grid
# ---------------------------------------------------------------------------

def plot_z_slice_grid(vol, meta, save=False, outdir="."):
    """One subplot per Z layer with a shared colour scale."""
    Nx, Ny, Nz = meta["Nx"], meta["Ny"], meta["Nz"]
    sx, sy, sz = meta["sx"], meta["sy"], meta["sz"]
    det = meta["target_detector"]

    vmax = float(vol.max())
    ncols = min(Nz, 8)
    nrows = (Nz + ncols - 1) // ncols

    fig, axes = plt.subplots(nrows, ncols, figsize=(2.8 * ncols, 2.8 * nrows))
    fig.suptitle(f"Z-Slice Grid — Detector {det}", fontsize=13)
    axes = np.array(axes).reshape(nrows, ncols)

    z_coords = np.linspace(-sz / 2, sz / 2, Nz)

    for zi in range(Nz):
        r, c = divmod(zi, ncols)
        ax = axes[r, c]
        ax.imshow(
            vol[:, :, zi].T,
            origin="lower",
            extent=[-sx/2, sx/2, -sy/2, sy/2],
            cmap="viridis",
            vmin=0,
            vmax=vmax,
            interpolation="nearest",
        )
        ax.set_title(f"z = {z_coords[zi]:+.2f} mm", fontsize=8)
        ax.set_xticks([])
        ax.set_yticks([])

    for zi in range(Nz, nrows * ncols):      # hide empty panels
        r, c = divmod(zi, ncols)
        axes[r, c].set_visible(False)

    # shared colour bar on the right
    fig.subplots_adjust(right=0.88, hspace=0.35, wspace=0.08)
    cbar_ax = fig.add_axes([0.90, 0.15, 0.015, 0.7])
    sm = plt.cm.ScalarMappable(
        cmap="viridis", norm=plt.Normalize(vmin=0, vmax=vmax)
    )
    fig.colorbar(sm, cax=cbar_ax, label="PPDF")

    _save_or_show(fig, save, outdir, f"ppdf_zslices_det{det}.png")


# ---------------------------------------------------------------------------
# Panel 3 — 3-D scatter of non-zero voxels
# ---------------------------------------------------------------------------

def plot_3d_scatter(vol, meta, threshold_pct=90, max_points=20_000,
                    save=False, outdir="."):
    """
    Scatter-plot voxels whose PPDF value exceeds `threshold_pct` of the
    non-zero population.  Colour and alpha are scaled by value to give a
    pseudo-volume appearance.
    """
    Nx, Ny, Nz = meta["Nx"], meta["Ny"], meta["Nz"]
    sx, sy, sz = meta["sx"], meta["sy"], meta["sz"]
    det = meta["target_detector"]

    # Physical voxel-centre coordinates
    xs = np.linspace(-sx / 2, sx / 2, Nx)
    ys = np.linspace(-sy / 2, sy / 2, Ny)
    zs = np.linspace(-sz / 2, sz / 2, Nz)

    # Threshold: operate only on non-zero voxels
    nonzero = vol[vol > 0]
    if nonzero.size == 0:
        print("  [3-D scatter] Volume is all zeros — skipping.")
        return
    thresh = float(np.percentile(nonzero, threshold_pct))
    mask = vol >= thresh

    xi, yi, zi = np.where(mask)
    vals = vol[xi, yi, zi]

    # Subsample if too many points (deterministic)
    if len(vals) > max_points:
        rng = np.random.default_rng(0)
        idx = rng.choice(len(vals), max_points, replace=False)
        xi, yi, zi, vals = xi[idx], yi[idx], zi[idx], vals[idx]

    x_w, y_w, z_w = xs[xi], ys[yi], zs[zi]

    # Normalise to [0, 1] for visual scaling
    v_min, v_max = vals.min(), vals.max()
    v_norm = (vals - v_min) / (v_max - v_min + 1e-12)

    # Build RGBA manually so per-point alpha works on mpl ≤ 3.9 (macOS).
    # Passing alpha= as a per-element array alongside edgecolors triggers a
    # "number of colors must match alpha values" error in mpl_toolkits/art3d.
    norm_obj = plt.Normalize(vmin=v_min, vmax=v_max)
    cmap_fn  = plt.cm.get_cmap("inferno")
    rgba = cmap_fn(norm_obj(vals))                          # (N, 4)
    rgba[:, 3] = np.clip(0.15 + 0.75 * v_norm, 0.0, 1.0)  # set alpha channel

    fig = plt.figure(figsize=(9, 7))
    ax = fig.add_subplot(111, projection="3d")

    ax.scatter(
        x_w, y_w, z_w,
        c=rgba,
        s=np.clip(4 + 36 * v_norm, 2, 40),
        edgecolors="none",
        depthshade=False,   # keep our manually set alpha intact
    )

    # Separate ScalarMappable for the colourbar
    sm = plt.cm.ScalarMappable(cmap="inferno", norm=norm_obj)
    plt.colorbar(sm, ax=ax, label="PPDF", fraction=0.025, pad=0.12)
    ax.set_xlabel("X (mm)")
    ax.set_ylabel("Y (mm)")
    ax.set_zlabel("Z (mm)")
    ax.set_xlim(-sx / 2, sx / 2)
    ax.set_ylim(-sy / 2, sy / 2)
    ax.set_zlim(-sz / 2, sz / 2)
    ax.set_title(
        f"3-D PPDF — Detector {det}\n"
        f"≥ p{threshold_pct:.0f} of non-zero voxels  ({len(vals):,} points shown)",
        fontsize=11,
    )
    ax.view_init(elev=25, azim=-55)
    plt.tight_layout()

    _save_or_show(fig, save, outdir, f"ppdf_3d_det{det}.png")


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _save_or_show(fig, save, outdir, filename):
    if save:
        out = os.path.join(outdir, filename)
        fig.savefig(out, dpi=150)
        print(f"  Saved: {out}")
        plt.close(fig)
    else:
        plt.show()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="3-D PPDF visualizer for pymatcal outputs.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("input", help="HDF5 file ('ppdf_volume' or 'ppdfs' dataset)")
    ap.add_argument(
        "--det-idx", type=int, default=0,
        help="Detector row index within a batch shard (ignored for single-det files)",
    )
    ap.add_argument(
        "--fov-size", type=float, nargs=3, metavar=("SX", "SY", "SZ"),
        default=None,
        help="FOV physical size in mm — required for single-det files that lack size attrs",
    )
    ap.add_argument(
        "--threshold-pct", type=float, default=90,
        help="Percentile of non-zero voxels shown in 3-D scatter",
    )
    ap.add_argument(
        "--max-points", type=int, default=20_000,
        help="Maximum number of voxels rendered in 3-D scatter",
    )
    ap.add_argument("--no-ortho",   action="store_true", help="Skip orthogonal-slice panel")
    ap.add_argument("--no-zslices", action="store_true", help="Skip Z-slice grid panel")
    ap.add_argument("--no-3d",      action="store_true", help="Skip 3-D scatter panel")
    ap.add_argument(
        "--save", action="store_true",
        help="Save figures to disk instead of showing interactively",
    )
    ap.add_argument(
        "--outdir", type=str, default=".",
        help="Output directory for saved figures",
    )
    args = ap.parse_args()

    # Load volume
    vol, meta = load_ppdf_volume(args.input, det_idx=args.det_idx)

    # Override / supply FOV size
    if args.fov_size is not None:
        meta["sx"], meta["sy"], meta["sz"] = args.fov_size
    elif any(np.isnan([meta["sx"], meta["sy"], meta["sz"]])):
        print(
            "ERROR: FOV size not found in the HDF5 file.\n"
            "Supply it with:  --fov-size SX SY SZ  (in mm)",
            file=sys.stderr,
        )
        sys.exit(1)

    print(
        f"Loaded  : {os.path.basename(args.input)}\n"
        f"Detector: {meta['target_detector']}\n"
        f"Shape   : ({meta['Nx']}, {meta['Ny']}, {meta['Nz']})\n"
        f"FOV     : {meta['sx']:.1f} × {meta['sy']:.1f} × {meta['sz']:.1f} mm\n"
        f"max PPDF: {vol.max():.4e}  |  non-zero: {(vol > 0).sum():,} voxels"
    )

    os.makedirs(args.outdir, exist_ok=True)

    if not args.no_ortho:
        print("Rendering orthogonal slices...")
        plot_orthogonal_slices(vol, meta, save=args.save, outdir=args.outdir)

    if not args.no_zslices:
        print("Rendering Z-slice grid...")
        plot_z_slice_grid(vol, meta, save=args.save, outdir=args.outdir)

    if not args.no_3d:
        print(f"Rendering 3-D scatter (p{args.threshold_pct:.0f} threshold)...")
        plot_3d_scatter(
            vol, meta,
            threshold_pct=args.threshold_pct,
            max_points=args.max_points,
            save=args.save,
            outdir=args.outdir,
        )


if __name__ == "__main__":
    main()
