# Paths
paths:
  input_tensor: "/vscratch/grp-rutaoyao/sid/data-test/scanner_layouts/mph_hourglass_single_position_base_3mm_18pinholes_rotated_elliptical.tensor"
  output_dir: "/vscratch/grp-rutaoyao/sid/data-test/mph_hourglass_single_position_base_3mm_18pinholes_rotated_elliptical/outputs/"

# FOV Configuration
fov:
  pixels: [512, 512]
  size_mm: [128, 128]
  center_mm: [0.0, 0.0]
  subdivisions: [4, 4] # Sub-FOV divisions

# Crystal Configuration
scanner:
  crystal_subdivisions: [1, 3] # Sub-crystal divisions
  mu_values: [3.5, 0.475]      # [mu_crystal, mu_plate]