# plot_ppdf.py

import numpy as np
import h5py
import matplotlib.pyplot as plt
import os
import torch # Using torch just to load the tensor for FOV params

# ==============================================================================
# MAIN SCRIPT EXECUTION
# ==============================================================================

if __name__ == "__main__":
    
    # --- 1. Configuration ---
    
    # A) Path to the single HDF5 file generated by calculate_ppdf_for_system.py
    #    *** YOU MUST UPDATE THIS PATH ***
    ppdf_filename = "/vscratch/grp-rutaoyao/Harsh/ALL_CONFIGS/nonmux/outputs_new/ppdf_results.hdf5"
    
    # B) FOV definition. 
    #    *** These MUST match the parameters used in calculate_ppdf_for_system.py ***
    #    to ensure the 1D data is reshaped into the correct 2D image.
    fov_config = {
        "n_pixels": torch.tensor([256, 256]),
        "mm_per_pixel": torch.tensor([0.5, 0.5]),
    }
    
    # C) Number of detector PPDFs to sum. 
    #    Set to -1 to sum all detectors in the file.
    #    Set to a smaller number (e.g., 100) for a quick preview.
    num_detectors_to_sum = -1

    # --- 2. Load PPDF Data ---
    
    if not os.path.exists(ppdf_filename):
        print(f"Error: PPDF file not found at '{ppdf_filename}'")
        print("Please ensure the PPDF calculation has run and the path is correct.")
        exit()

    print(f"Loading PPDF data from: {ppdf_filename}")
    with h5py.File(ppdf_filename, "r") as f:
        if "ppdfs" not in f:
            print(f"Error: Dataset 'ppdfs' not found in {ppdf_filename}.")
            exit()
        
        # Load all or a subset of the data
        if num_detectors_to_sum == -1:
            ppdf_data = f["ppdfs"][:]
        else:
            ppdf_data = f["ppdfs"][:num_detectors_to_sum, :]
    
    print(f"Successfully loaded PPDFs for {ppdf_data.shape[0]} detectors.")

    # --- 3. Process Data ---
    
    # Sum the PPDFs of all loaded detectors to create a system sensitivity map
    # Each row is the PPDF for one detector, so we sum along axis 0 (the rows).
    sensitivity_map_1d = np.sum(ppdf_data, axis=0)
    
    # Reshape the 1D vector into a 2D image
    fov_y, fov_x = fov_config['n_pixels']
    try:
        # Note: The order is (height, width), which corresponds to (y, x)
        sensitivity_map_2d = sensitivity_map_1d.reshape((fov_y, fov_x))
    except ValueError as e:
        print(f"Error: Could not reshape the PPDF data into a ({fov_y}, {fov_x}) image.")
        print(f"The loaded data has {sensitivity_map_1d.size} elements, but {fov_y*fov_x} were expected.")
        print("Please ensure the fov_config in this script matches the one used for calculation.")
        exit()

    # --- 4. Plot the Sensitivity Map ---
    
    print("Generating sensitivity map plot...")
    
    # Calculate the plot extent to label the axes correctly in millimeters
    mm_x, mm_y = fov_config['mm_per_pixel']
    x_min_mm = -float(mm_x) * fov_x / 2
    x_max_mm =  float(mm_x) * fov_x / 2
    y_min_mm = -float(mm_y) * fov_y / 2
    y_max_mm =  float(mm_y) * fov_y / 2
    plot_extent = [x_min_mm, x_max_mm, y_min_mm, y_max_mm]

    # Create the plot
    plt.figure(figsize=(9, 7))
    # Use origin='lower' so (0,0) is at the bottom-left, standard for scientific plots
    plt.imshow(sensitivity_map_2d, cmap='viridis', origin='lower', extent=plot_extent)
    plt.colorbar(label='System Sensitivity (Sum of PPDFs)')
    plt.title('System Sensitivity Map')
    plt.xlabel('X (mm)')
    plt.ylabel('Y (mm)')
    plt.grid(True, linestyle=':', color='white', alpha=0.5)
    
    # Construct an output filename based on the input
    output_plot_filename = os.path.splitext(ppdf_filename)[0] + "_sensitivity_map.png"
    plt.savefig(output_plot_filename, dpi=300)
    
    print(f"\nSuccessfully saved sensitivity map to:\n  {output_plot_filename}")
    plt.show()